/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.socialsteps.data.model;

import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType Activities.
 *
 * @since 2023-02-27
 */
@PrimaryKeys({"activityId"})
public final class Activities extends CloudDBZoneObject {
    private String activityId;

    private String uid;

    private String activityType;

    private String activityStartTime;

    private String duration;

    private Integer calories;

    private String totalDistance;

    private String speedStatistics;

    private String heartRateStatistics;

    private String totalStep;

    private String stepCadenceStatistics;

    private String runningFormStatistics;

    public Activities() {
        super(Activities.class);
    }

    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    public String getActivityId() {
        return activityId;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUid() {
        return uid;
    }

    public void setActivityType(String activityType) {
        this.activityType = activityType;
    }

    public String getActivityType() {
        return activityType;
    }

    public void setActivityStartTime(String activityStartTime) {
        this.activityStartTime = activityStartTime;
    }

    public String getActivityStartTime() {
        return activityStartTime;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getDuration() {
        return duration;
    }

    public void setCalories(Integer calories) {
        this.calories = calories;
    }

    public Integer getCalories() {
        return calories;
    }

    public void setTotalDistance(String totalDistance) {
        this.totalDistance = totalDistance;
    }

    public String getTotalDistance() {
        return totalDistance;
    }

    public void setSpeedStatistics(String speedStatistics) {
        this.speedStatistics = speedStatistics;
    }

    public String getSpeedStatistics() {
        return speedStatistics;
    }

    public void setHeartRateStatistics(String heartRateStatistics) {
        this.heartRateStatistics = heartRateStatistics;
    }

    public String getHeartRateStatistics() {
        return heartRateStatistics;
    }

    public void setTotalStep(String totalStep) {
        this.totalStep = totalStep;
    }

    public String getTotalStep() {
        return totalStep;
    }

    public void setStepCadenceStatistics(String stepCadenceStatistics) {
        this.stepCadenceStatistics = stepCadenceStatistics;
    }

    public String getStepCadenceStatistics() {
        return stepCadenceStatistics;
    }

    public void setRunningFormStatistics(String runningFormStatistics) {
        this.runningFormStatistics = runningFormStatistics;
    }

    public String getRunningFormStatistics() {
        return runningFormStatistics;
    }

}
