/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.socialsteps.data.model;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType Friendship.
 *
 * @since 2023-02-27
 */
@PrimaryKeys({"friendShipId"})
@Indexes({"sentRequestDate:sentRequestDate"})
public final class Friendship extends CloudDBZoneObject {
    private String friendShipId;

    @NotNull
    @DefaultValue(stringValue = "")
    private String user1;

    @NotNull
    @DefaultValue(stringValue = "")
    private String user2;

    private String status;

    private String sentRequestDate;

    private String user1name;

    private String user2name;

    private String user1Photo;

    public Friendship() {
        super(Friendship.class);
        this.user1 = "";
        this.user2 = "";
    }

    public void setFriendShipId(String friendShipId) {
        this.friendShipId = friendShipId;
    }

    public String getFriendShipId() {
        return friendShipId;
    }

    public void setUser1(String user1) {
        this.user1 = user1;
    }

    public String getUser1() {
        return user1;
    }

    public void setUser2(String user2) {
        this.user2 = user2;
    }

    public String getUser2() {
        return user2;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setSentRequestDate(String sentRequestDate) {
        this.sentRequestDate = sentRequestDate;
    }

    public String getSentRequestDate() {
        return sentRequestDate;
    }

    public void setUser1name(String user1name) {
        this.user1name = user1name;
    }

    public String getUser1name() {
        return user1name;
    }

    public void setUser2name(String user2name) {
        this.user2name = user2name;
    }

    public String getUser2name() {
        return user2name;
    }

    public void setUser1Photo(String user1Photo) {
        this.user1Photo = user1Photo;
    }

    public String getUser1Photo() {
        return user1Photo;
    }

}
