/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.socialsteps.data.model;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType GroupInformation.
 *
 * @since 2023-02-27
 */
@PrimaryKeys({"groupID"})
@Indexes({"groupName:groupName", "groupID:groupID"})
public final class GroupInformation extends CloudDBZoneObject {
    private String groupID;

    @NotNull
    @DefaultValue(stringValue = "")
    private String groupName;

    @NotNull
    @DefaultValue(stringValue = "")
    private String groupAdmin;

    @NotNull
    @DefaultValue(stringValue = "")
    private String targetType;

    private String stepTarget;

    private String calorieTarget;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean isPrivate;

    public GroupInformation() {
        super(GroupInformation.class);
        this.groupName = "";
        this.groupAdmin = "";
        this.targetType = "";
        this.isPrivate = false;
    }

    public void setGroupID(String groupID) {
        this.groupID = groupID;
    }

    public String getGroupID() {
        return groupID;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupAdmin(String groupAdmin) {
        this.groupAdmin = groupAdmin;
    }

    public String getGroupAdmin() {
        return groupAdmin;
    }

    public void setTargetType(String targetType) {
        this.targetType = targetType;
    }

    public String getTargetType() {
        return targetType;
    }

    public void setStepTarget(String stepTarget) {
        this.stepTarget = stepTarget;
    }

    public String getStepTarget() {
        return stepTarget;
    }

    public void setCalorieTarget(String calorieTarget) {
        this.calorieTarget = calorieTarget;
    }

    public String getCalorieTarget() {
        return calorieTarget;
    }

    public void setIsPrivate(Boolean isPrivate) {
        this.isPrivate = isPrivate;
    }

    public Boolean getIsPrivate() {
        return isPrivate;
    }

}
