/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.socialsteps.data.model;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType GroupMembers.
 *
 * @since 2023-02-27
 */
@PrimaryKeys({"groupMembersID"})
@Indexes({"groupID:groupID", "userID:userID"})
public final class GroupMembers extends CloudDBZoneObject {
    private String groupMembersID;

    @NotNull
    @DefaultValue(stringValue = "")
    private String groupID;

    @NotNull
    @DefaultValue(stringValue = "")
    private String userID;

    public GroupMembers() {
        super(GroupMembers.class);
        this.groupID = "";
        this.userID = "";
    }

    public void setGroupMembersID(String groupMembersID) {
        this.groupMembersID = groupMembersID;
    }

    public String getGroupMembersID() {
        return groupMembersID;
    }

    public void setGroupID(String groupID) {
        this.groupID = groupID;
    }

    public String getGroupID() {
        return groupID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getUserID() {
        return userID;
    }

}
