/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.socialsteps.data.model;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType MessagingItem.
 *
 * @since 2023-02-27
 */
@PrimaryKeys({"messagingId"})
public final class MessagingItem extends CloudDBZoneObject {
    private String messagingId;

    @NotNull
    @DefaultValue(stringValue = "")
    private String user1;

    @NotNull
    @DefaultValue(stringValue = "")
    private String user2;

    private String lastMessage;

    private String lastUpdateTime;

    public MessagingItem() {
        super(MessagingItem.class);
        this.user1 = "";
        this.user2 = "";
    }

    public void setMessagingId(String messagingId) {
        this.messagingId = messagingId;
    }

    public String getMessagingId() {
        return messagingId;
    }

    public void setUser1(String user1) {
        this.user1 = user1;
    }

    public String getUser1() {
        return user1;
    }

    public void setUser2(String user2) {
        this.user2 = user2;
    }

    public String getUser2() {
        return user2;
    }

    public void setLastMessage(String lastMessage) {
        this.lastMessage = lastMessage;
    }

    public String getLastMessage() {
        return lastMessage;
    }

    public void setLastUpdateTime(String lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    public String getLastUpdateTime() {
        return lastUpdateTime;
    }

}
