/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.socialsteps.data.model;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType MessageItem.
 *
 * @since 2023-02-27
 */
@PrimaryKeys({"messageId"})
public final class MessageItem extends CloudDBZoneObject {
    private String messageId;

    @NotNull
    @DefaultValue(stringValue = "")
    private String senderId;

    @NotNull
    @DefaultValue(stringValue = "")
    private String receiverId;

    private String text;

    private String additionalData;

    private String type;

    private String sendTime;

    @NotNull
    @DefaultValue(stringValue = "")
    private String messagingId;

    public MessageItem() {
        super(MessageItem.class);
        this.senderId = "";
        this.receiverId = "";
        this.messagingId = "";
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public String getMessageId() {
        return messageId;
    }

    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public String getSenderId() {
        return senderId;
    }

    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }

    public String getReceiverId() {
        return receiverId;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getText() {
        return text;
    }

    public void setAdditionalData(String additionalData) {
        this.additionalData = additionalData;
    }

    public String getAdditionalData() {
        return additionalData;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getType() {
        return type;
    }

    public void setSendTime(String sendTime) {
        this.sendTime = sendTime;
    }

    public String getSendTime() {
        return sendTime;
    }

    public void setMessagingId(String messagingId) {
        this.messagingId = messagingId;
    }

    public String getMessagingId() {
        return messagingId;
    }

}
