/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.socialsteps.data.model;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType Notifications.
 *
 * @since 2023-02-27
 */
@PrimaryKeys({"notificationID"})
@Indexes({"notificationID:notificationID"})
public final class Notifications extends CloudDBZoneObject {
    private String notificationID;

    @NotNull
    @DefaultValue(stringValue = "")
    private String notificationType;

    @NotNull
    @DefaultValue(stringValue = "")
    private String user1;

    private String user1Photo;

    private String user1Name;

    private String user2;

    private String notificationDate;

    private String postID;

    private Boolean isRead;

    private String recordCreationTime;

    @DefaultValue(stringValue = "")
    private String additionalString;

    public Notifications() {
        super(Notifications.class);
        this.notificationType = "";
        this.user1 = "";
        this.additionalString = "";
    }

    public void setNotificationID(String notificationID) {
        this.notificationID = notificationID;
    }

    public String getNotificationID() {
        return notificationID;
    }

    public void setNotificationType(String notificationType) {
        this.notificationType = notificationType;
    }

    public String getNotificationType() {
        return notificationType;
    }

    public void setUser1(String user1) {
        this.user1 = user1;
    }

    public String getUser1() {
        return user1;
    }

    public void setUser1Photo(String user1Photo) {
        this.user1Photo = user1Photo;
    }

    public String getUser1Photo() {
        return user1Photo;
    }

    public void setUser1Name(String user1Name) {
        this.user1Name = user1Name;
    }

    public String getUser1Name() {
        return user1Name;
    }

    public void setUser2(String user2) {
        this.user2 = user2;
    }

    public String getUser2() {
        return user2;
    }

    public void setNotificationDate(String notificationDate) {
        this.notificationDate = notificationDate;
    }

    public String getNotificationDate() {
        return notificationDate;
    }

    public void setPostID(String postID) {
        this.postID = postID;
    }

    public String getPostID() {
        return postID;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setRecordCreationTime(String recordCreationTime) {
        this.recordCreationTime = recordCreationTime;
    }

    public String getRecordCreationTime() {
        return recordCreationTime;
    }

    public void setAdditionalString(String additionalString) {
        this.additionalString = additionalString;
    }

    public String getAdditionalString() {
        return additionalString;
    }

}
