/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.socialsteps.data.model;

import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType Posts.
 *
 * @since 2023-02-27
 */
@PrimaryKeys({"postId"})
public final class Posts extends CloudDBZoneObject {
    private String postId;

    private String userId;

    private Integer postType;

    private String activityId;

    private String sharedDate;

    private String targetSteps;

    private String targetCalories;

    private String activityType;

    private String reachedSteps;

    private String reachedCalories;

    private String name;

    private String username;

    private String photoUrl;

    private String sharedDateMillis;

    public Posts() {
        super(Posts.class);
    }

    public void setPostId(String postId) {
        this.postId = postId;
    }

    public String getPostId() {
        return postId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserId() {
        return userId;
    }

    public void setPostType(Integer postType) {
        this.postType = postType;
    }

    public Integer getPostType() {
        return postType;
    }

    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    public String getActivityId() {
        return activityId;
    }

    public void setSharedDate(String sharedDate) {
        this.sharedDate = sharedDate;
    }

    public String getSharedDate() {
        return sharedDate;
    }

    public void setTargetSteps(String targetSteps) {
        this.targetSteps = targetSteps;
    }

    public String getTargetSteps() {
        return targetSteps;
    }

    public void setTargetCalories(String targetCalories) {
        this.targetCalories = targetCalories;
    }

    public String getTargetCalories() {
        return targetCalories;
    }

    public void setActivityType(String activityType) {
        this.activityType = activityType;
    }

    public String getActivityType() {
        return activityType;
    }

    public void setReachedSteps(String reachedSteps) {
        this.reachedSteps = reachedSteps;
    }

    public String getReachedSteps() {
        return reachedSteps;
    }

    public void setReachedCalories(String reachedCalories) {
        this.reachedCalories = reachedCalories;
    }

    public String getReachedCalories() {
        return reachedCalories;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUsername() {
        return username;
    }

    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    public String getPhotoUrl() {
        return photoUrl;
    }

    public void setSharedDateMillis(String sharedDateMillis) {
        this.sharedDateMillis = sharedDateMillis;
    }

    public String getSharedDateMillis() {
        return sharedDateMillis;
    }

}
