/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.hms.socialsteps.data.model;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType Users.
 *
 * @since 2023-02-27
 */
@PrimaryKeys({"uid"})
@Indexes({"uid:uid"})
public final class Users extends CloudDBZoneObject {
    private String uid;

    private String fullName;

    private String username;

    private String photo;

    private Integer age;

    private Integer height;

    private Integer weight;

    private String gender;

    private String targetCalories;

    @DefaultValue(stringValue = "0")
    private String caloriesBurned;

    @DefaultValue(stringValue = "0")
    private String caloriesIntake;

    private String targetSteps;

    private String dailyStepsCount;

    private String exerciseFrequency;

    private String weightPreference;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean permissionToShareInfo;

    private String lastUpdatedTime;

    private String lastDailyStepsUpdatedTime;

    private String lastDailyCaloriesUpdatedTime;

    private Boolean isPrivate;

    public Users() {
        super(Users.class);
        this.caloriesBurned = "0";
        this.caloriesIntake = "0";
        this.permissionToShareInfo = false;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUid() {
        return uid;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getFullName() {
        return fullName;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUsername() {
        return username;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getPhoto() {
        return photo;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getAge() {
        return age;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getHeight() {
        return height;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getGender() {
        return gender;
    }

    public void setTargetCalories(String targetCalories) {
        this.targetCalories = targetCalories;
    }

    public String getTargetCalories() {
        return targetCalories;
    }

    public void setCaloriesBurned(String caloriesBurned) {
        this.caloriesBurned = caloriesBurned;
    }

    public String getCaloriesBurned() {
        return caloriesBurned;
    }

    public void setCaloriesIntake(String caloriesIntake) {
        this.caloriesIntake = caloriesIntake;
    }

    public String getCaloriesIntake() {
        return caloriesIntake;
    }

    public void setTargetSteps(String targetSteps) {
        this.targetSteps = targetSteps;
    }

    public String getTargetSteps() {
        return targetSteps;
    }

    public void setDailyStepsCount(String dailyStepsCount) {
        this.dailyStepsCount = dailyStepsCount;
    }

    public String getDailyStepsCount() {
        return dailyStepsCount;
    }

    public void setExerciseFrequency(String exerciseFrequency) {
        this.exerciseFrequency = exerciseFrequency;
    }

    public String getExerciseFrequency() {
        return exerciseFrequency;
    }

    public void setWeightPreference(String weightPreference) {
        this.weightPreference = weightPreference;
    }

    public String getWeightPreference() {
        return weightPreference;
    }

    public void setPermissionToShareInfo(Boolean permissionToShareInfo) {
        this.permissionToShareInfo = permissionToShareInfo;
    }

    public Boolean getPermissionToShareInfo() {
        return permissionToShareInfo;
    }

    public void setLastUpdatedTime(String lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    public String getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    public void setLastDailyStepsUpdatedTime(String lastDailyStepsUpdatedTime) {
        this.lastDailyStepsUpdatedTime = lastDailyStepsUpdatedTime;
    }

    public String getLastDailyStepsUpdatedTime() {
        return lastDailyStepsUpdatedTime;
    }

    public void setLastDailyCaloriesUpdatedTime(String lastDailyCaloriesUpdatedTime) {
        this.lastDailyCaloriesUpdatedTime = lastDailyCaloriesUpdatedTime;
    }

    public String getLastDailyCaloriesUpdatedTime() {
        return lastDailyCaloriesUpdatedTime;
    }

    public void setIsPrivate(Boolean isPrivate) {
        this.isPrivate = isPrivate;
    }

    public Boolean getIsPrivate() {
        return isPrivate;
    }

}
